title: Software Developer
author: Jaelyn Coles
email: jaelyncoles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Come with me as I begin a new career in Software Development
# social links

github_username:  jaelyncoles

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
